// Copyright Epic Games, Inc. All Rights Reserved.
// Copy one chunk's visible splat count into a global per-chunk array.

#include "/Engine/Public/Platform.ush"

uint ChunkIndex;
StructuredBuffer<uint> VisibleCountBuffer;
RWStructuredBuffer<uint> RWChunkVisibleCounts;

[numthreads(1, 1, 1)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
	RWChunkVisibleCounts[ChunkIndex] = VisibleCountBuffer[0];
}
